### ISSUE TITLE
Not Collecting data 

### ISSUE THREAD

**Issue by matty0511** [psilvaazevedo/TICK-Speedtest-Grafana#2]
I am not sure where to even start with why this isnt working. I am somewhat new to influxdb/telegraf/grafana.  I followed the steps as instructed but its not collecting any data.

**Comment by pedrolsazevedo** [comment]
Hi, the most common problem is that the speedtest CLI requires you to accept the EULA before run the test, i've updated the readme to make this step more clear.
Could you, please, check step four in Configuration?
Feel free to ask any question.

**Comment by pedrolsazevedo** [comment]
Hello, did the speedtest-cli configuration worked out for you?

**Comment by pedrolsazevedo** [comment]
I will close this issue, but if you need any assistance fell free to open a new issue and I will try to help you.
